[package]
name = "todo-server"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["secrets", "json"] }
serde = "*"
argon2 = "0.6.0"
sqlx = "0.7.0"
todo-shared = { path = "../todo-shared" }

[dependencies.rocket_db_pools]
version = "0.2.0"
features = ["sqlx_postgres"]
